-- CreateTable
CREATE TABLE "Lead" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT,
    "treatment" TEXT,
    "procedure" TEXT,
    "message" TEXT,
    "city" TEXT,
    "age" TEXT,
    "pincode" TEXT,
    "consent" BOOLEAN NOT NULL DEFAULT false,
    "source" TEXT,
    "formName" TEXT NOT NULL DEFAULT 'Website Leads',
    "status" TEXT NOT NULL DEFAULT 'new',
    "whatsappNumber" TEXT,
    "womansAgeBracket" TEXT,
    "tryingDuration" TEXT,
    "isWhatsapp" TEXT,
    "appointmentDateTime" TEXT,
    "professionalBackground" TEXT,
    "digitalExperience" TEXT,
    "mainStruggle" TEXT,
    "revenueMechanism" TEXT,
    "platformPriorities" TEXT,
    "ultimateGoal" TEXT,
    "investmentMindset" TEXT,
    "pageUrl" TEXT,
    "telecrmSynced" BOOLEAN NOT NULL DEFAULT false,
    "telecrmId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lead_pkey" PRIMARY KEY ("id")
);
