/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as IseeuRouteImport } from './routes/iseeu'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubmissionsRouteImport } from './routes/api/submissions'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IseeuRoute = IseeuRouteImport.update({
  id: '/iseeu',
  path: '/iseeu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubmissionsRoute = ApiSubmissionsRouteImport.update({
  id: '/api/submissions',
  path: '/api/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/iseeu': typeof IseeuRoute
  '/thank-you': typeof ThankYouRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/iseeu': typeof IseeuRoute
  '/thank-you': typeof ThankYouRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/iseeu': typeof IseeuRoute
  '/thank-you': typeof ThankYouRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/submissions': typeof ApiSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin-dashboard'
    | '/iseeu'
    | '/thank-you'
    | '/api/leads'
    | '/api/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin-dashboard'
    | '/iseeu'
    | '/thank-you'
    | '/api/leads'
    | '/api/submissions'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin-dashboard'
    | '/iseeu'
    | '/thank-you'
    | '/api/leads'
    | '/api/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  IseeuRoute: typeof IseeuRoute
  ThankYouRoute: typeof ThankYouRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiSubmissionsRoute: typeof ApiSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iseeu': {
      id: '/iseeu'
      path: '/iseeu'
      fullPath: '/iseeu'
      preLoaderRoute: typeof IseeuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/submissions': {
      id: '/api/submissions'
      path: '/api/submissions'
      fullPath: '/api/submissions'
      preLoaderRoute: typeof ApiSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  IseeuRoute: IseeuRoute,
  ThankYouRoute: ThankYouRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiSubmissionsRoute: ApiSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
